# Generated by Django 4.2.8 on 2023-12-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0002_alter_leaf_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaf',
            name='observed_date',
        ),
    ]
