# Generated by Django 4.2.8 on 2023-12-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0003_remove_leaf_observed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
