# Generated by Django 4.2.8 on 2024-01-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0009_disease'),
    ]

    operations = [
    ]
