# Generated by Django 4.2.8 on 2024-01-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0010_auto_20240111_0029'),
    ]

    operations = [
    ]
