# Generated by Django 4.2.8 on 2024-01-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0012_auto_20240111_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='rememberMe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='uniqueId',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
