# Generated by Django 4.2.8 on 2024-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0013_userregister_rememberme_userregister_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='uniqueId',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
