# Generated by Django 4.2.8 on 2024-01-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0014_alter_userregister_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='rememberMe',
            field=models.BooleanField(default=0),
        ),
    ]
